spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentmanager?characterEncoding=UTF-8
    username: root
    password: a1414914
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

#  thymeleaf:
#    mode: HTML
#    encoding: utf-8
#    cache: false
#    prefix: classpath:/templates/

